### PR TITLE
fix: Timer Skip Survival

### PR DESCRIPTION
**Pull request by ChristopheCVB**
Fix timer reseting to 2mins when skip is done with less than 2mins remaining when playing Survival mode

### CODE REVIEW

**Comment by GreepTheSheep** [comment]
Thank you, I'll test it tomorrow. Can you just change the merge branch to 'develop' please? Thanks 👍

**Comment by ChristopheCVB** [comment]
> Thank you, I'll test it tomorrow. Can you just change the merge branch to 'develop' please? Thanks 👍

Oh sorry, yes, just read the contributing and saw my mistake

**Comment by Flink91** [comment]
nice

**Review by GreepTheSheep — APPROVED** [review]
Thanks

**Pull request merged**
